#!/usr/bin/python3

import argparse

from dockerlaunch.main import run

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--indocker', help='Set Python 3 script to run inside the container', default=None)
    parser.add_argument('command', help='Daemon command')
    args = parser.parse_args()

    run(indocker=args.indocker)
