site_name: Go-Smart Simulation Framework Documentation
pages:
    - Home: 'index.md'
    - Modules:
        - NumaAlternating: 'numa-alternating.md'
        - NumaCellState: 'numa-cell-state.md'
        - NumaHeatSolver: 'numa-heat-solver.md'
        - NumaIRE: 'numa-ire.md'
        - NumaInitBoundaryConditions: 'numa-init-boundary-conditions.md'
        - NumaInitBoundaryConditions_gs: 'numa-init-boundary-conditions_gs.md'
        - NumaLegacyCellState: 'numa-legacy-cell-state.md'
        - NumaLegacyHeatSolver: 'numa-legacy-heat-solver.md'
        - NumaLesion: 'numa-lesion.md'
        - NumaPowerField: 'numa-power-field.md'
        - NumaPowerGenerator: 'numa-power-generator.md'
        - NumaProgress: 'numa-progress.md'
        - NumaTM: 'numa-tm.md'
        - OptimizedHeatSolver: 'optimized-heat-solver.md'
theme: amelia
