site_name: GSSF Supplementary Elmer Modules
pages:
    - Home: 'index.md'
    - Modules:
        - NumaAlternating: 'numa-alternating.md'
        - NumaCellState: 'numa-cell-state.md'
        - NumaIRE: 'numa-ire.md'
        - NumaLesion: 'numa-lesion.md'
        - NumaPowerField: 'numa-power-field.md'
        - NumaPowerGenerator: 'numa-power-generator.md'
        - NumaProgress: 'numa-progress.md'
        - NumaTM: 'numa-tm.md'
        - OptimizedHeatSolver: 'optimized-heat-solver.md'
theme: cyborg
