#!/usr/bin/env python3

# This file is part of the Go-Smart Simulation Architecture (GSSA).
# Go-Smart is an EU-FP7 project, funded by the European Commission.
#
# Copyright (C) 2013-  NUMA Engineering Ltd. (see AUTHORS file)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from autobahn.asyncio.wamp import ApplicationRunner
import argparse

from gosmart.server.client import GoSmartSimulationClientComponent


def launch(x):
    cpt = GoSmartSimulationClientComponent(
        x,
        gssa_file=input_file,
        subdirectory=subdirectory,
        output_files=output_files,
        definition_file=definition_file,
        skip_clean=skip_clean
    )
    return cpt


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--gssa-file", help="GSSA-XML simulation description", default="original.xml")
    parser.add_argument("--subdir", help="subdirectory of /tmp containing input files", default=".")
    parser.add_argument("--host", help="host to connect to", default="localhost")
    parser.add_argument("--websocket-port", help="port hosting websocket", default="9000", type=int)
    parser.add_argument("--skip-clean", help="do not clean up after run", action='store_true', default=False)
    parser.add_argument("--output", help="file to request as output", nargs='+', default="output.vtp")
    parser.add_argument("--definition", help="file containing text of the definition node (which should exist but be empty in the GSSA file", default=None)
    args = parser.parse_args()
    input_file = args.gssa_file

    host = args.host
    websocket_port = args.websocket_port
    subdirectory = args.subdir
    output_files = args.output
    definition_file = args.definition
    skip_clean = args.skip_clean
    runner = ApplicationRunner(url="ws://%s:%d/ws" % (host, websocket_port), realm="realm1")
    runner.run(launch)
