#!/usr/bin/env python3

# This file is part of the Go-Smart Simulation Architecture (GSSA).
# Go-Smart is an EU-FP7 project, funded by the European Commission.
#
# Copyright (C) 2013-  NUMA Engineering Ltd. (see AUTHORS file)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from autobahn.asyncio.wamp import ApplicationRunner

from gssa.server import GoSmartSimulationServerComponent
from gssa.database import SQLiteSimulationDatabase

import argparse
import uuid
import logging
import gosmart_sf_config


logging.getLogger('watchdog.observers.inotify_buffer').setLevel(logging.DEBUG)
print(gosmart_sf_config.etc_location)


# Start up a new simulation server object with the Autobahn WAMP application
# Note that we explicitly define the type of DB store - this should be made
# configurable
def launch(x, server_id, ignore_development=False):
    component = GoSmartSimulationServerComponent(x, server_id, lambda: SQLiteSimulationDatabase("simulations.sqlite3"), ignore_development)

    return component

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", help="host to connect to", default="localhost")
    parser.add_argument("--websocket-port", help="port hosting websocket", default="9000", type=int)
    parser.add_argument("--sftp-host", help="server hosting SFTP", default="localhost")
    parser.add_argument("--sftp-port", help="port hosting SFTP", default="9001", type=int)
    parser.add_argument("--key-file", help="file for authenticating to SFTP", default="id_rsa")
    parser.add_argument("--ignore-development", action='store_true', help="do not process cases with parameter DEVELOPMENT truthy")
    parser.add_argument("sid", help="Server UUID (should be subdirectory of current directory)", default=None, nargs='?')
    args = parser.parse_args()

    # Assign arguments to sensible variables
    key_file = args.key_file
    host = args.host
    websocket_port = args.websocket_port
    sftp_port = args.sftp_port
    sftp_host = args.sftp_host
    ignore_development = args.ignore_development

    # If the user has not supplied a particular server identity (that can be
    # used to exclusively refer to this persistent set of info in the DB) then
    # we generate a UUID
    if not args.sid:
        server_id = str(uuid.uuid4())
    else:
        server_id = args.sid

    runner = ApplicationRunner(url="ws://%s:%d/ws" % (host, websocket_port), realm="realm1")
    runner.run(lambda x: launch(x, server_id=server_id, ignore_development=ignore_development))
