#!/usr/bin/python2.7

# This file is part of the Go-Smart Simulation Architecture (GSSA).
# Go-Smart is an EU-FP7 project, funded by the European Commission.
#
# Copyright (C) 2013-  NUMA Engineering Ltd. (see AUTHORS file)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from gssf2.preprocessor import preprocessor
import sys


# TODO: is this script still needed? Needs work if so, removed otherwise

def main():
    runname = sys.argv[0]
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    radius = float(sys.argv[3])
    x = float(sys.argv[4])
    y = float(sys.argv[5])
    z = float(sys.argv[6])

    preprocessor.Preprocessor(runname, input_file, output_file, radius, x, y, z)

if __name__ == "__main__":
    main()
